version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    env_file:
      - '.env'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/var/lib/redis/data
      - ./opt/homebrew/etc/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6350:6379"
    env_file:
      - '.env'
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    env_file:
      - '.env'
    command: bundle exec sidekiq
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - RAILS_ENV=${RAILS_ENV}
    env_file:
      - '.env'