services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "bindu123"
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - pgdata:/var/lib/postgresql/data



  web:
    build:
      context: /Users/moyinho20/shri/open-source-billing
      dockerfile: Dockerfile
    command: sh -c "bundle exec rails server -b 0.0.0.0"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
     - "3005:3000"

networks:
  mynetwork:
    name: open-source-billing_mynetwork

volumes:
  pgdata: