source 'https://rubygems.org'
ruby '3.2.2'
gem 'rails', '~> 7.0'

gem 'sprockets', '~> 4'
gem 'sprockets-rails'
gem 'pg', '1.3.4'
gem 'matrix'
# gem 'activerecord-mysql2-adapter'
gem 'psych', '< 4'
gem 'logger'
gem 'devise'
gem 'devise-encryptable'
gem 'slim-rails'
gem 'twitter-bootstrap-rails'
gem 'rails-settings-cached', '0.6.6'
# gem 'rake', '< 11.0'
# gem 'responders'

gem 'sass-rails', '>= 6'
# gem 'yajl-ruby', '~>1.3.1'
gem 'coffee-rails'
# gem 'therubyracer', '0.12.3', :platforms => :ruby
gem 'uglifier'
gem 'sassc'
# gem 'active_link_to', '1.0.3'
gem 'jquery-rails'
gem 'nested_form'
gem 'kaminari'
gem 'acts_as_archival'
gem 'paranoia', '~> 2.6'
gem 'daemons'
gem 'hashie_rails'
group :development do
  # gem 'better_errors', '2.1.1'
  gem "binding_of_caller", ">= 0.6.9"
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 6.0'
  # gem 'awesome_print', '1.7.0'
  # gem 'quiet_assets'
  # gem 'copyright-header', '1.0.15'
  gem 'capistrano'
  gem 'capistrano-rails'
  # gem "letter_opener", '1.4.1'
  gem 'listen'
  gem 'dotenv-rails', groups: [:development, :test]
end
# gem 'capistrano-rvm', '0.1.2'
# gem 'browser'
gem 'gon', '6.3.1'
# gem 'rest-client', '1.8.0'
# gem 'slim', '3.0.7'
# gem 'paypal-sdk-rest', '1.4.6'
# gem 'activemerchant'
gem 'paper_trail', '10.3.1'
# gem 'carrierwave'
# gem 'tinymce-rails', '4.3.13'
# gem 'fullcalendar-rails', '2.0.2.0'
# gem 'momentjs-rails', '2.11.1'
gem 'prawn'
gem 'prawn-table'


gem 'activerecord-session_store'
gem 'stripe'
gem 'figaro'

group :test do
  gem 'shoulda-matchers', '~> 4.0'
  gem 'shoulda', '~> 4.0'
  gem 'rspec-its', '1.2.0'
  gem 'factory_bot_rails'
  gem 'factory_bot'
  gem 'faker'
end

# gem 'money', '~>  6.5.0'
gem 'osb_api', path: 'vendor/engines/osb_api'
# gem 'tzinfo-data'
# To use Jbuilder templates for JSON
# gem 'jbuilder', '~> 2.0'
# gem 'oauth', '0.4.7'
# gem 'oauth2'
# gem 'roxml'
gem 'nokogiri'
# gem 'quickbooks-ruby'
# gem 'qbo_api'
# gem 'ruby-freshbooks', '0.4.1'
gem 'rolify'
gem 'puma'


gem 'elasticsearch-model'
gem 'elasticsearch-rails'

gem 'exception_notification-rake', '0.3.1'

# gem 'whenever', '0.9.7'
gem 'js_cookie_rails', '1.0.1'
gem 'i18n-js', '~> 3.0', '>= 3.0.5'
gem 'simple_form', '5.0.0'
gem 'cocoon'
# gem 'nouislider-rails', '~> 8.2', '>= 8.2.1'
gem 'simple_token_authentication'
gem 'sidekiq', '>= 5.2.7'
gem 'sidekiq-symbols'
gem "pundit"
gem 'groupdate'
gem 'chartkick'
gem "hashid-rails"
gem 'public_activity'
gem 'to_words'
# gem 'trackstamps'
gem 'jquery-infinite-pages'
# gem "introjs-rails"
gem 'jquery-validation-rails'
# gem 'bigdecimal', '~> 1.2', '>= 1.2.7'
gem 'webpacker'
gem 'hammerjs-rails'
gem 'rack-cors'
